[supervisord]
nodaemon=false
logfile=/share/immich/log/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:postgres]
command=/usr/lib/postgresql/%(ENV_PG_VERSION)s/bin/postgres -D /share/immich/postgres
user=postgres
autostart=true
autorestart=true
priority=10
stdout_logfile=/share/immich/log/postgres.log
stderr_logfile=/share/immich/log/postgres.log

[program:redis]
command=redis-server --save "" --appendonly no --bind 127.0.0.1
user=redis
autostart=true
autorestart=true
priority=20
stdout_logfile=/share/immich/log/redis.log
stderr_logfile=/share/immich/log/redis.log

[program:immich-ml]
command=python3 /usr/src/immich-ml/app/main.py
directory=/usr/src/immich-ml
user=node
autostart=%(ENV_IMMICH_ML_ENABLED)s
autorestart=true
priority=30
environment=MACHINE_LEARNING_CACHE_FOLDER="/share/immich/ml-cache"
stdout_logfile=/share/immich/log/immich-ml.log
stderr_logfile=/share/immich/log/immich-ml.log

[program:immich-server]
command=node /usr/src/app/dist/main
directory=/usr/src/app
user=node
autostart=true
autorestart=true
priority=40
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[eventlistener:quit-on-immich-server-crash]
command=bash -c "printf 'READY\n'; while read line; do kill -SIGTERM $PPID; done < /dev/stdin"
events=PROCESS_STATE_FATAL
