name: Wordpress
version: 6.7.2
slug: wordpress
description: Wordpress
url: https://github.com/simon-adriaanse/hassio-addons/tree/master/wordpress
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: ghcr.io/simon-adriaanse/wordpress-{arch}
# webui: http://[HOST]:[PORT:80]
map:
  - ssl:rw
  - media:rw
  - share:rw
ingress: true
init: false
panel_icon: mdi:web-box
options:
  document_root: /share/htdocs
  php_ini: default
  default_conf: default
  default_ssl_conf: default
  website_name: null
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  init_commands: []
schema:
  document_root: str
  php_ini: str
  default_conf: str
  default_ssl_conf: str
  website_name: str
  username: str?
  password: password?
  ssl: bool
  certfile: str
  keyfile: str
  init_commands:
    - str?
ports:
  80/tcp: 80
  443/tcp: 8324
ports_description:
  80/tcp: Web interface http
  443/tcp: SSL Web interface
