services:
  db:
    image: mysql:5.7
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress_homeassistant
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - wordpress_network
      
    # phpmyadmin
  phpmyadmin:
    depends_on:
      - Topsecret
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
volumes:
  db_data:
  wp_data:

networks:
  wordpress_network: