name: Convert CRLF to LF

permissions:
  contents: write  # Required to commit and push CRLF to LF changes
  pull-requests: read  # Allows reading pull request details (write is not needed)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  fix-crlf:
    name: Fix CRLF Endings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v4

      - name: Fix CRLF line endings
        run: |
          find . -type f \( -name "*.sh" -o -name "*.py" -o -name "*.yml" -o -name "*.yaml" -o -name "*.json" -o -name "*.md" \) \
            | xargs grep -lU $'\r' 2>/dev/null \
            | xargs -r dos2unix

      - name: Commit if needed
        uses: EndBug/add-and-commit@v9
        with:
          message: "Github bot : CRLF corrected"
          default_author: github_actions
